### ISSUE TITLE
Issue running phylowgs pipeline

### ISSUE THREAD

**Issue by mkinnaman** [MathOnco/EvoFreq#15]
Hi Team,

Love this concept as I am using both CALDER and phylowgs on a longitudinal WGS dataset. I keep running into this issue when trying to run the phylowgs pipeline:

pdf('./evofreqs.pdf', width=8, height=4, onefile = T)
for (i in 1:length(f$all)){
  clone_dynamics_df <- get_evofreq(tree_data[[i]][,c(5,length(colnames(tree_data)))], clones=tree_data[[i]]$clone, parents=tree_data[[i]]$parent, clone_cmap = "jet")
  p <- plot_evofreq(evofreq_df)
  print(p)
}
**Error in f : object 'f' not found**

When I try to run on my Calder data I get the following error:

> calder.data <- parse_calder(theSoln, theFile)
**Error in seq.default(grep("U", lines, fixed = T) + 1, length(lines)) :
  'from' must be of length 1**

Not sure if its an issue with my setup or dataset but would appreciate your input.

**Comment by nathanlee543** [comment]
I am interested in running this on some CALDER outputs. I get the same error as @mkinnaman:
```
> calder.data <- parse_calder(theSoln, theFile)
Error in seq.default(grep("U", lines, fixed = T) + 1, length(lines)) : 
  'from' must be of length 1
```
It looks like the grep search of the .dot file returns any line that has a "U", so if any of the clones contain genes with a "U" in the name, then the grep search returns that line as well. It looks like the grep search is supposed to return just the line number of the line that is only "U"? I didn't see if mkinnaman was able to find a way around this error. Thanks for your input! Very useful package.

**Comment by rschenck** [comment]
Thanks for the compliment. Hope you're finding the package useful short of this error. I thought we'd pushed a fix for this, but suppose not.

For sake of getting you a solution as fast as possible, if you omit the 'U' from the gene name, does that fix the problem?

**Comment by mkinnaman** [comment]
Also i dont think this function exists anymore "long_to_wide_size_df" however it is in the code for the Evofreq_parsers and this is an issue at the parse_calder step

**Comment by nathanlee543** [comment]
For now I'll just write my own version of the parse_calder function that searches for an exact match of "U". 

I also run into mkinnaman's problem about the "long_to_wide_size_df" function.  Is the long_to_wide_freq_ready function equivalent to the long_to_wide_size_df function? I notice that in the README, long_to_wide_size_df is mentioned in the comment, but the available function is used in the code:

> 104 | # Use the long_to_wide_size_df function to get the right data structure.
> 105 | wide_df <- long_to_wide_freq_ready(long_pop_sizes_df = example.easy.long.sizes,
